### ISSUE TITLE
Add post-commit hook for prettier

### ISSUE THREAD

**Issue by icambron** [icambron/luxon#27]
You can run `gulp format` or `gulp lint!` before committing but it's easy to forget. Would be nice if something just tacked on commits that did that.

**Comment by JemBijoux** [comment]
Are you open to this running pre-commit rather than post-commit? The prettier documentation recommends a simple way to get set up with pre-commit hooks. I've submitted a PR for it.

The nice thing about this approach is that it ensures any file modified is cleaned up before the commit message is even entered (and all automatically without gulp commands needed).

**Comment by icambron** [comment]
Yup, that approach works for me. Closing this.
